require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FleetsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Fleet. As you add validations to Fleet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {instance_type: "t2.micro", instance_count: 2}
  }

  let(:invalid_attributes) {
    {instance_type: "fake instance type", instance_count: 0}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FleetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all fleets as @fleets" do
      fleet = Fleet.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:fleets)).to eq([fleet])
    end
  end

  describe "GET show" do
    it "assigns the requested fleet as @fleet" do
      fleet = Fleet.create! valid_attributes
      get :show, {:id => fleet.to_param}, valid_session
      expect(assigns(:fleet)).to eq(fleet)
    end
  end

  describe "GET new" do
    it "assigns a new fleet as @fleet" do
      get :new, {}, valid_session
      expect(assigns(:fleet)).to be_a_new(Fleet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Fleet" do
        expect {
          post :create, {:fleet => valid_attributes}, valid_session
        }.to change(Fleet, :count).by(1)
      end

      it "assigns a newly created fleet as @fleet" do
        post :create, {:fleet => valid_attributes}, valid_session
        expect(assigns(:fleet)).to be_a(Fleet)
        expect(assigns(:fleet)).to be_persisted
      end

      it "redirects to the created fleet" do
        post :create, {:fleet => valid_attributes}, valid_session
        expect(response).to redirect_to(Fleet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fleet as @fleet" do
        post :create, {:fleet => invalid_attributes}, valid_session
        expect(assigns(:fleet)).to be_a_new(Fleet)
      end

      it "re-renders the 'new' template" do
        post :create, {:fleet => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fleet" do
      fleet = Fleet.create! valid_attributes
      expect {
        delete :destroy, {:id => fleet.to_param}, valid_session
      }.to change(Fleet, :count).by(-1)
    end

    it "redirects to the fleets list" do
      fleet = Fleet.create! valid_attributes
      delete :destroy, {:id => fleet.to_param}, valid_session
      expect(response).to redirect_to(fleets_url)
    end
  end

end
